// Default visual settings for the workbench tuning page.
// These are starting values — the developer tunes them live,
// then "Records" to export as visualSettings.json.

export const DEFAULTS = {
  knob: {
    arcWidth: 4,
    arcSweepDeg: 270,
    arcGapPosition: 'bottom',
    bodyRadius: 24,
    bodyGradientInner: null,
    bodyGradientOuter: null,
    bodyBorderWidth: 1,
    bodyBorderColor: null,
    dropShadowBlur: 8,
    dropShadowOffsetY: 3,
    dropShadowColor: 'rgba(0,0,0,0.5)',
    indicatorLength: 0.6,
    indicatorEndLength: 0.85,
    indicatorWidth: 2,
    indicatorColor: null,
    activeArcColor: null,
    inactiveArcColor: null,
    activeArcGlow: false,
    activeArcGlowBlur: 6,
    labelSize: 10,
    labelSpacing: 0.5,
    valueSize: 13,
    totalWidth: 80,
    totalHeight: 95,
    hoverBrightness: 1.15,
  },

  slider: {
    trackThickness: 2,
    trackColor: null,
    activeTrackColor: null,
    activeTrackGlow: false,
    activeTrackGlowBlur: 4,
    handleWidth: 14,
    handleHeight: 24,
    handleBevelDepth: 2.5,
    handleBaseColor: null,
    handleTopFaceBrightness: 1.25,
    handleBottomFaceBrightness: 0.65,
    handleLeftFaceBrightness: 1.15,
    handleRightFaceBrightness: 0.8,
    handleGrooveCount: 2,
    handleGrooveColor: 'rgba(0,0,0,0.3)',
    handleGrooveWidth: 1,
    handleIndicatorWidth: 2,
    handleIndicatorColor: null,
    handleDropShadow: true,
    handleShadowBlur: 6,
    handleShadowOffsetY: 2,
    handleShadowColor: 'rgba(0,0,0,0.4)',
    handleBorderRadius: 2,
    tickLength: 5,
    tickWidth: 1,
    tickCount: 10,
    tickColor: null,
    tickOffset: 3,
    labelSize: 10,
    valueSize: 12,
    horizontalHeight: 38,
    verticalWidth: 42,
    verticalHeight: 170,
  },

  piano: {
    height: 44,
    whiteKeyColor: null,
    blackKeyColor: null,
    selectedColor: null,
    blackKeyHeightRatio: 0.62,
    blackKeyWidthRatio: 0.58,
    keyBorderRadius: 2,
    keyGap: 1,
    borderColor: null,
    borderWidth: 1,
    showLabels: true,
    labelSize: 9,
    labelColor: '#666666',
    hoverBrightness: 1.1,
  },

  waveform: {
    blobAmpScale: 0.45,
    blobFillOpacity: 0.35,
    blobStrokeOpacity: 0.8,
    blobStrokeWidth: 1.5,
    blobColor: null,
    blobSmoothing: 'light',
    gridLaneHeight: 14,
    gridWhiteNoteColor: null,
    gridBlackNoteColor: null,
    gridLineColor: null,
    gridLineWidth: 0.5,
    selectedLaneHighlight: null,
    noteLabelSize: 10,
    noteLabelColor: null,
    noteLabelWidth: 40,
    timeLabelSize: 9,
    timeLabelColor: null,
    modeLabelSize: 11,
    emptyStateSize: 14,
    showTimeAxis: true,
    showNoteLabels: true,
    borderColor: null,
    borderWidth: 1,
  },

  harmonic: {
    nodeRadius: 7,
    nodeDefaultGradStart: null,
    nodeDefaultGradEnd: null,
    nodeModifiedColor: null,
    nodeBorderWidth: 1.5,
    nodeBorderColor: 'rgba(255,255,255,0.3)',
    nodeGlow: true,
    nodeGlowBlur: 8,
    nodeGlowColor: null,
    stemWidth: 1.5,
    stemColor: null,
    stemOpacity: 0.6,
    labelSize: 9,
    labelColor: null,
    labelOffsetY: -12,
    spectrumFillOpacity: 0.12,
    spectrumStrokeOpacity: 0.5,
    spectrumStrokeWidth: 1,
    spectrumColor: null,
    axisLabelSize: 10,
    axisLabelColor: null,
    axisLineColor: null,
    axisLineWidth: 0.5,
    ceilingGuideColor: 'rgba(245,166,35,0.5)',
    ceilingGuideWidth: 1,
    disabledOpacity: 0.35,
    borderColor: null,
    borderWidth: 1,
  },
};
